### PR TITLE
Backport upstream PR #99

### PR DESCRIPTION
**Pull request by avano**
@Croway fyi

since this changes the project version from 2.6.9-SNAPSHOT to 3.0.0-SNAPSHOT, should also the target branch name be updated to match the version?

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by Croway** [comment]
> 

I'd say so, @cunningt wdyt?

**Comment by cunningt** [comment]
@avano @Croway These changes sound good to me - I still think there's a possibility that we may take a new branch from upstream at some point once the sb3 commits here go to upstream, but if it would help testing if we take these changes and do another build we should definitely do it.

**Review by cunningt — APPROVED** [review]

**Comment by Croway** [comment]
Since we do not know if or when the PR upstream will be merged, and the narayana released, I'd say to create a new branch

**Comment by cunningt** [comment]
@Croway If you go ahead and merge it, I'll rename the branch for 3.0.0 and / change the build configs.

**Pull request merged**
